### ISSUE TITLE
PPOM Circle Cropper is not saving cropped photos with enabled AJAX add to cart button

### ISSUE THREAD

**Issue by SumLord** [Codeinwp/woocommerce-product-addon#12]
Hi, 
PPOM Circle Cropper does not work with the enabled AJAX add to cart button. 
You can see it here: https://memoriesinyourjewel.com/product/skewed-heart/
AJAX add to cart button is enabled at Woocommerce -> Products -> Add to cart behaviour.
Thanks in advance for a fix

**Comment by mskapusuz** [comment]
hi @SumLord 

Thank you for using PPOM For WooCommerce.

**Image Cropper** is a part of the **PPOM Pro**, therefore please let us know on your themeisle.com account. You can reach us by creating a ticket. We would like to help you there.

I'm closing this issue. Have a great day!
