### ISSUE TITLE
New groups of field gets duplicated once created and saved with contet

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/woocommerce-product-addon#128]
### Description

Creating a new group with some fields in it, will add two groups with the same name, the duplicate one being empty(no fieds).

### Step-by-step reproduction instructions

1. Create a new group
2. Name it and save it empty
3. Add a field to the new group(I tested with Radio)
4. Save fields
5. Now check the page with all the PPOM fields and you will see the group duplicated with an empty one

### Screenshots, screen recording, code snippet or Help Scout ticket

[Video](https://vertis.d.pr/v/YoU6q7) about the issue

![Markup on 2023-04-05 at 12:13:54](https://user-images.githubusercontent.com/26867648/230037061-29aefdab-51a2-45b5-bc7b-32ca3b08e914.png)

### Environment info

https://pastebin.com/tsvnGEe5

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by girishpanchal30** [comment]
Hey @stefan-cotitosu,

I can't replicate this issue, can you please share your test instance details?
Ref: https://www.loom.com/share/6827e5762e044a54b731ea4e14ce1c59

Thanks

**Comment by stefan-cotitosu** [comment]
hey @girishpanchal30, sure.

http://neve-conflicts.stefancoti.com/wp-admin/
stefan
Admin123

**Comment by girishpanchal30** [comment]
Hey @stefan-cotitosu,

Still, [I can't replicate](https://tinyurl.com/2kgbd6c4) this issue with your instance but now I've added an error notice if fields are empty.
Please check with this PR https://github.com/Codeinwp/woocommerce-product-addon/pull/147 and do let me know if you have any issues.
Ref: https://tinyurl.com/2pwvy2ov

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 I didn't manage to replicate the issue but i tested the notice if fields are empty and it works as expected 👍 
@stefan-cotitosu Can you please check if the issue is fixed for you using the linked PR? I'll move it to **Ready to merge** when you confirm 🙏

**Comment by irinelenache** [comment]
@stefan-cotitosu Thank you for checking, i'll move this to **Ready to merge** 🚀
