### ISSUE TITLE
Compatibility with HPOS

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/woocommerce-product-addon#157]
### Description

A user mentioned that PPOM is listed as incompatible with HPOS and asked if it will be made compatible in the future.

### Step-by-step reproduction instructions

-

### Screenshots, screen recording, code snippet or Help Scout ticket

Asked [here](https://wordpress.org/support/topic/hpos-compatible/).

### Is the issue you are reporting a regression

No

**Comment by MarinescuLucia** [comment]
+1 https://wordpress.org/support/topic/hpos-support-for-ppom/

**Comment by MarinescuLucia** [comment]
+1 https://wordpress.org/support/topic/is-ppom-hpos-compatible/

**Comment by MarinescuLucia** [comment]
+1 https://wordpress.org/support/topic/hpos-compatible/#post-16962007

**Comment by stefan-cotitosu** [comment]
@vytisbulkevicius, any chance to prioritize this? HPOS (High-Performance Order Storage) seems to be a core functionality of WooCommerce, and our PPOM plugin (both of its versions) is flagged as incompatible, being required to disable our plugin for using this feature of the WooCommerce plugin.

Context of the feature mentioned - https://woocommerce.com/document/high-performance-order-storage/#section-2

Example from the Dashboard:

![hpos-ppom-issue](https://github.com/Codeinwp/woocommerce-product-addon/assets/26867648/1974c483-9320-432f-a892-a34212b88e67)

**Comment by vytisbulkevicius** [comment]
Hey @girishpanchal30,

Can you review this to see how much effort it's needed to make PPOM compatible with HPOS?
https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#declaring-extension-incompatibility

Thanks!

**Comment by stefan-cotitosu** [comment]
+1 https://wordpress.org/support/topic/woocommerce-hpos-cot-5/

**Comment by stefan-cotitosu** [comment]
+1 https://wordpress.org/support/topic/hpos-support-for-ppom/

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius,

I've reviewed this issue and fixed the `HPOS` compatibility issue with the attached PR #167, PRO - Codeinwp/ppom-pro/pull/247

Now it seems the `HPOS` setting working fine.
Ref: https://tinyurl.com/2bjjrtzv

Thanks

**Comment by rodica-andronache** [comment]
@girishpanchal30 everything's working well 👍

**Comment by vytisbulkevicius** [comment]
This is fixed and released @stefan-cotitosu
Please inform the users on wp.org threads and resolve those threads @Codeinwp/support, thanks!
