### ISSUE TITLE
Add Dimensions Calculation in Font Picker PPOM Field.

### ISSUE THREAD

**Issue by RohanSharma2598** [Codeinwp/woocommerce-product-addon#162]
### What problem does this address?

This is requested by a Customer. He sells stickers and it is really crucial for him to provide the dimensions of the sticker as well, along with the Font Family that is being picked.

You can see the working of the dimensions here that customer wants:
https://demo.vinylletteringdesigner.com/2/product/vinyl-lettering/

### What is your proposed solution?

Add a height and width field with the Font Picker that customer can pick and that height and width values will be visible around the font as well and you can see in the link above.
![image](https://github.com/Codeinwp/woocommerce-product-addon/assets/65424424/32adb36e-bdbd-4a38-87ff-973653db2475)

### Will this feature require documentation? (Optional)

None

**Comment by Soare-Robert-Daniel** [comment]
Not sure on how this custom angular app is related to our product.

<img width="1636" alt="Screenshot 2024-08-26 at 14 37 15" src="https://github.com/user-attachments/assets/e643534e-9966-4e21-9666-4070c2b5df10">
