### ISSUE TITLE
PPOM Permissions setting is working only for the Administrator role

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/woocommerce-product-addon#179]
### Description

In PPOM settings, there is [an option](https://vertis.d.pr/i/k0yl3y) to allow other user roles to edit the PPOM fields. Any role added there will not work, except the Administrator role. 
Video showing the issue - https://vertis.d.pr/v/0LaJbH

Old related issue - https://github.com/Codeinwp/woocommerce-product-addon/issues/9

### Step-by-step reproduction instructions

1. In PPOM Settings, add some user roles to the PPOM Permissions field
2. Create a user with the added role
3. Login with the new user and check if PPOM fields are available

### Screenshots, screen recording, code snippet or Help Scout ticket

https://vertis.d.pr/v/0LaJbH

### Environment info

WordPress 6.4 / WooCommerce 8.2.1 / PPOM 32.0.9 / PHP 7.4

### Is the issue you are reporting a regression

No

**Comment by irinelenache** [comment]
Ticket - https://secure.helpscout.net/conversation/2413047876/391929?folderId=212390

**Comment by girishpanchal30** [comment]
@irinelenache I've reviewed this issue and fixed it with this PR https://github.com/Codeinwp/woocommerce-product-addon/pull/180

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and the issue is fixed now, thank you 🚀
