### ISSUE TITLE
Products in multiple categories don't show all fields

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/woocommerce-product-addon#181]
### What problem does this address?

A product being in two categories, cat1 and cat2, and two PPOM groups of fields being set to apply as follows:

Group1 to products in cat1
Group2 to products in cat2

In this case, only Group1 of fields will be displayed to the current product.

### What is your proposed solution?

Display the fields from all Groups on the product page in this case.

Requested here - https://wordpress.org/support/topic/products-in-multiple-categories-3/#post-17192382

### Will this feature require documentation? (Optional)

No.

**Comment by Soare-Robert-Daniel** [comment]
I think this is related to https://github.com/Codeinwp/woocommerce-product-addon/issues/259
