### ISSUE TITLE
PPOM Texter Popup is too big

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/woocommerce-product-addon#183]
### Description

Depending on the image size used when configuring the PPOM Texter, its dimension is different, so the user might need to scroll to see the whole content, which is not very user-friendly.

Also, in my case, I was using Neve and a header on 3 rows, so I could not even see the text area inside the texter.

Identified while working on this - https://secure.helpscout.net/conversation/2420296070/392746?folderId=212385

### Step-by-step reproduction instructions

1. Go to PPOM Texter 
2. Configure a new texter and use a large image
3. Go to WooCommerce > PPOM Fields
4. Create a new group using the PPOM Texter field
5. Go to the front page and check the results

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="1680" alt="image" src="https://github.com/Codeinwp/woocommerce-product-addon/assets/86592992/496e3c44-9e64-4b9f-b0fa-07cca1810812">

See live behavior here - https://root.stefancoti.com/product/chicken-sticks/

### Is the issue you are reporting a regression

No

**Comment by irinelenache** [comment]
@AndreeaCristinaRadacina @girishpanchal30 This is how it works for me with some larger images https://vertis.d.pr/v/xRpXwl Is this expected? I didn't exactly understand the issue

**Comment by girishpanchal30** [comment]
@irinelenache It might be a cache issue, can you please verify whether my changes are there or not in your test environment?
Ref: https://github.com/Codeinwp/woocommerce-product-addon/commit/2fc6bf15ca831320e1dd186f0566546304ba55aa

**Comment by irinelenache** [comment]
@girishpanchal30 I checked again on a fresh instance and it works fine now, sorry about the caching issue 🙏
