### ISSUE TITLE
Keep the file name in the cart

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/woocommerce-product-addon#191]
### What problem does this address?

A user asked if keeping the original file name inside the cart is possible.

Ref: https://secure.helpscout.net/conversation/2415148038/392206?folderId=931544

### What is your proposed solution?

Maintain the name of the uploaded file.

### Will this feature require documentation? (Optional)

No.

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://secure.helpscout.net/conversation/2537359225/408260?viewId=212385

**Comment by Soare-Robert-Daniel** [comment]
We can go with this pattern for saving files:

```
<original file name>.<random hash>.<file extension>
```

E.g.:

```
cat-1.asdf234.png
```
