### ISSUE TITLE
Disable the mouse pointer from the group options

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/woocommerce-product-addon#199]
On the Group Page, the labels for basic settings display a mouse pointer when hovered over, even though they are not clickable.

<img width="1680" alt="image" src="https://github.com/Codeinwp/woocommerce-product-addon/assets/86592992/cfabcf4e-ab0b-40d3-9a73-9726ed0f6caf">

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina Fixed it here https://github.com/Codeinwp/woocommerce-product-addon/pull/360
