### ISSUE TITLE
Update settings descriptions

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/woocommerce-product-addon#200]
While working on a request, I noticed several spelling mistakes in PPOM Price descriptions, as well as confusing phrasal:
<img width="1497" alt="image" src="https://github.com/Codeinwp/woocommerce-product-addon/assets/86592992/ce57a5ef-fb21-4758-8f1f-0aab7d423ab9">

- Overrides the core product price on archive and product pages if PPOM field options have a price.
- Hides the core price of Variable Products under the "Price" title when PPOM Fields are attached.
-  Hides the option price in Select/Radio/Checkbox/Image inputs that display the price along with the label.
- etc

**Comment by selul** [comment]
here we can use the oportunity to review all descriptions and titles.

**Comment by selul** [comment]
here we can be also more courageous and review the organization of those settings and see if maybe we can group them better. 

Also the sidebar names maybe it worth looking at if is worth it, to remove it maybe and keep just tabs and organize all the tabs better.
