### ISSUE TITLE
Total amount in cart not correct for decimal numbers in Measurement input

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/woocommerce-product-addon#204]
### Description

A user reported that the amount is not displayed correctly in the cart when the measurement input contains decimal numbers. I managed to replicate this issue.

Ref - https://secure.helpscout.net/conversation/2436729906/394921?viewId=212385

### Step-by-step reproduction instructions

1. Go to a meta group
2. Insert the measurement input
3. Provide a step suitable for decimals, like 0.1
4. Do the same for another measurement input
5. Go to the product and insert some values
6. Check the cart

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="1592" alt="image" src="https://github.com/Codeinwp/woocommerce-product-addon/assets/86592992/cd381d97-47dc-49cc-a762-aa7f25cf1f86">
<img width="860" alt="image" src="https://github.com/Codeinwp/woocommerce-product-addon/assets/86592992/f8edd0bc-26e8-4b84-b2b7-cc5ed0b8904f">

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
Hey @AndreeaCristinaRadacina

I have checked this issue and it seems working from my end, can you please share your test instance details here.

Thanks

**Comment by AndreeaCristinaRadacina** [comment]
Hey @girishpanchal30,
I tried again, but I can't seem to replicate the issue anymore. Maybe it was related to the cache. Thank you!

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina Thank you for the reply, I'm going to close this issue
