### ISSUE TITLE
Clarify the product page table

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/woocommerce-product-addon#205]
A user asked about the pro options advantages: meta fields repeater, cart edit, Fields Popup, Quantities pack.

I have some questions/suggestions regarding these:

- meta fields repeater - we have two types of repeaters in PPOM: [Conditional Repeater ](https://docs.themeisle.com/article/1700-personalized-product-meta-manager#conditional-repeater)and [PPOM Repeater](https://docs.themeisle.com/article/1700-personalized-product-meta-manager#conditional-repeater) - we should clarify which one of them is and also we can mention both, as they are both part of pro
- fields popup - it's not described anywhere on the page, unlike the cart edit, which is described at some point.

**Comment by selul** [comment]
yes, we can address in docs if needed.
