### ISSUE TITLE
Mention the Enquiry Form on the product page as PRO feature

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/woocommerce-product-addon#209]
The enquiry form is a pro feature; however, it is not listed anywhere. Also, we should consider renaming it before; Grammarly tries to correct it anytime I use it in the phrases.
<img width="1680" alt="image" src="https://github.com/Codeinwp/woocommerce-product-addon/assets/86592992/52a9d368-d9a0-43c3-a551-65213ac5778d">

I found it on the https://themeisle.com/plugins/ppom-pro/?utm_source=themeisle&utm_medium=product&utm_campaign#pricing page listed as "inquiry", but in the plugin, it appears as Enquiry.

**Comment by vytisbulkevicius** [comment]
Added it to the list 👌
