### ISSUE TITLE
Plugin conflict due to general selectors

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/woocommerce-product-addon#214]
### Description

A user reported that PPOM made his h4 tags inherit the collapse style settings.

I was able to replicate this on my instance.
ref: https://secure.helpscout.net/conversation/2443308950/395691/

### Step-by-step reproduction instructions

1. Create a meta group 
2. Insert collapse field
3. Insert a text field
4. Go to WooCommerce > Settings > PPOM Settings > Addons > Collapse
5. Set colors for the collapse elements
6. Go on the frontend and expand the accordion
7. Check the other h4 tags on the page

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="1513" alt="image" src="https://github.com/Codeinwp/woocommerce-product-addon/assets/86592992/bbf0c8af-ebf9-4473-a8e1-5727f989a9cb">
<img width="1492" alt="image" src="https://github.com/Codeinwp/woocommerce-product-addon/assets/86592992/6be4a8d9-5778-4171-9ee9-509bd32ffd28">
https://vertis.d.pr/v/y86v3T

### Is the issue you are reporting a regression

No

**Comment by irinelenache** [comment]
@poonam279 Can you try to test this fix as part of the QA knowledge-sharing initiative?

**Comment by poonam279** [comment]
@irinelenache Sure, I will try this tomorrow.
