### ISSUE TITLE
URL field of the first option in Image DropDown has a different placeholder

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/woocommerce-product-addon#220]
While working on a ticket, I noticed that the first option in the Image Dropdown input has a "Description" placeholder instead of "URL".

Also, maybe we can use caps for "URL" as well.

<img width="1680" alt="image" src="https://github.com/Codeinwp/woocommerce-product-addon/assets/86592992/d2c8b47b-294b-4091-8671-ef83e0e5eee3">

ref:https://secure.helpscout.net/conversation/2459526803/397606?viewId=212385

**Comment by girishpanchal30** [comment]
Hey @AndreeaCristinaRadacina

I have checked in my local environment and every image dropdown fields have decription placeholder.

I could not found url placeholder.

Can you please share test environment.

Thanks

**Comment by AndreeaCristinaRadacina** [comment]
I also checked on a fresh instance, and the issue doesn't occur anymore there.
Thanks for checking!
