### ISSUE TITLE
Dropdown input doesn't respect set dimensions

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/woocommerce-product-addon#221]
### Description

While working on a ticket I noticed that in the images dropdown input, the width and height dimensions are not respected on the frontend.,

### Step-by-step reproduction instructions

1. Go to the meta fields
2. Insert image dropdown input
3. Add a value for the image width and image height (e.g. 20)
4. Upload some images in the options tab
5. Save the settings, attach it to a product and check how it looks

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="1596" alt="image" src="https://github.com/Codeinwp/woocommerce-product-addon/assets/86592992/936402d0-0c85-4e5e-a846-fc73fa495526">
<img width="1506" alt="image" src="https://github.com/Codeinwp/woocommerce-product-addon/assets/86592992/e38a9c95-4f11-43ce-b904-743bf2a6334a">
<img width="1390" alt="image" src="https://github.com/Codeinwp/woocommerce-product-addon/assets/86592992/c378996f-7404-4030-a5b5-eae0f4428116">

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
Hey @AndreeaCristinaRadacina

Add `px` suffix after the width and height value. e.g `100px`

Thanks
