### ISSUE TITLE
Update Cart button cannot be clicked after changes are made in the edit popup

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/woocommerce-product-addon#224]
### Description

A user reported that the Update Cart button cannot be clicked.

Ref: https://secure.helpscout.net/conversation/2460322805/397708?viewId=212385

I was able to replicate this issue. It happens when changes are made through Cart Edit Popup, and not by changing the value on the cart page directly.

### Step-by-step reproduction instructions

1. Enable the fields popup (in Products > Select a Product > PPOM Fields)
2. Enable cart edit (in WooCommerce > Settings > PPOM Settings > Addons > Cart Edit)
3. Enable popup cart edit
4. Go to a PPOM product
5. Make some configurations in the popup
6. Go to the cart page
7. Click on Fields Popup
8. Update the quantity and click on Update
9. Check on the cart page that the Update Cart button doesn't work

### Screenshots, screen recording, code snippet or Help Scout ticket

https://vertis.d.pr/v/g794Oz

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
Hey @AndreeaCristinaRadacina,

It seems the WooCommerce update cart button disabled itself on page load, and the PPOM cart update is working fine with the popup as well. 
Ref: https://github.com/woocommerce/woocommerce/blob/761954909195b183560594827894ccf5a2d232d3/plugins/woocommerce/client/legacy/js/frontend/cart.js#L142

I believe we can't remove the `disabled` attribute during the popup cart update process.

cc @vytisbulkevicius

Thanks
