### ISSUE TITLE
File Input appears inside the Conditions but no option can be used

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/woocommerce-product-addon#229]
While working on a ticket, I noticed that if we have a file input and we want to display another input (e.g. Select) based on the existence of the file input, it is not possible.

More precisely, I created a select input and opened the conditions tab. Inside the dropdown, I can select the File Input meta, but the last dropdown is empty (as expected since the file input does not have options). That being the case, I cannot restrict Select Input's visibility based on the existence of the File Input.

Ref: https://secure.helpscout.net/conversation/2466624874/398751?viewId=212385
Screenshot: https://vertis.d.pr/i/M75LFd

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://secure.helpscout.net/conversation/2543334379/409886?viewId=212385

The point is that we can extend the conditions to work for more input fields or grey out the inputs that are not suitable in the conditions tab.

e.g. in the above ticket, the user asks why he cannot insert a value in the conditions tab so that input will appear only if the Measure input is greater than <value>, which is not possible. It works only for inputs that have conditions in that dropdown.

**Comment by Soare-Robert-Daniel** [comment]
Same as https://github.com/Codeinwp/woocommerce-product-addon/issues/275#issuecomment-2306641549

**Comment by selul** [comment]
part of
