### ISSUE TITLE
Enhance Conditions Tab

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/woocommerce-product-addon#232]
At the moment, if you go to the conditions tab while working on a meta field and insert more conditions, you are not able to delete the last one. To do this, you need to delete and recreate the one above it:
<img width="1436" alt="image" src="https://github.com/Codeinwp/woocommerce-product-addon/assets/86592992/91e51d6f-b51a-441b-89a8-9b6d1b300e2f">

I believe we can make things easier and use two buttons for the last field as we have in Add Options:
<img width="696" alt="image" src="https://github.com/Codeinwp/woocommerce-product-addon/assets/86592992/0f4706a8-ac22-4be4-b79c-6468c3ce78c5">

**Comment by selul** [comment]
to fix this we can add minus and plus to the last field, however keeping just minus for last.

**Comment by girishpanchal30** [comment]
I've added some improvements to resolve this issue, Please check with this [PR](https://github.com/Codeinwp/woocommerce-product-addon/pull/367)
