### ISSUE TITLE
Cumulate the attached meta groups

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/woocommerce-product-addon#259]
### What problem does this address?

A user reported that there is a discrepancy in how PPOM cumulates the attached fields.

ref:https://secure.helpscout.net/conversation/2515915878/405301?viewId=212385

I am not sure if it's a bug or a feature request, but I will share the steps:

Scenario 1 - PPOM Dashboard
1. Create 2 meta groups
2. On the PPOM page, click on the attach button for the first group and assign it to a product
3. Check the product's page to make sure the PPOM group is there
4. Go back to the PPOM page and attach the other meta group
5. Check the product page and you'll see the first group is not displayed anymore

Second scenario - Individual product
1. Go to the individual product's page
2. Attach more meta groups and save the settings
<br><img width="1259" alt="image" src="https://github.com/Codeinwp/woocommerce-product-addon/assets/86592992/df785b2f-0663-4018-86f1-6dcb1130dd0f"><br>
3. Go to the product's page and you'll see all of them
<br><img width="1287" alt="image" src="https://github.com/Codeinwp/woocommerce-product-addon/assets/86592992/f2ad26be-f0dd-46f8-bf79-83f3e8e24692"><br>

### What is your proposed solution?

Ensure consistency between these scenarios.

### Will this feature require documentation? (Optional)

None

**Comment by Soare-Robert-Daniel** [comment]
To be consistent, we need to make the attachment to consider the other present groups in parts like this:

https://github.com/Codeinwp/woocommerce-product-addon/blob/5c14b9ecce897fcd2664c3ef3c4a40c98ede2d5d/classes/admin.class.php#L282

<img width="827" alt="Screenshot 2024-08-23 at 12 28 51" src="https://github.com/user-attachments/assets/ed663411-f3cd-489d-bd1e-b9fc9d135890">
