### ISSUE TITLE
Predefined values not working after the update

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/woocommerce-product-addon#260]
### Description

A user reported that the default values no longer work after the update. He has radio inputs with options, where the name of the option is used as default value, but the changes are not reflected on live website.

ref: https://secure.helpscout.net/conversation/2526814758/406626?viewId=212385

### Step-by-step reproduction instructions

1. Insert a radio button
2. Add an option
3. Use the option's name in the default value area

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="1489" alt="image" src="https://github.com/Codeinwp/woocommerce-product-addon/assets/86592992/e23557bd-2c05-42ea-875e-acee5c23572a">
<img width="693" alt="image" src="https://github.com/Codeinwp/woocommerce-product-addon/assets/86592992/7c265301-d23b-4d97-ab48-feed1f7ac026">

URL: https://merchprint.se/produkt/test/

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://wordpress.org/support/topic/pre-set-values/

**Comment by GrigoreMihai** [comment]
@AndreeaCristinaRadacina Could you help me a bit confirming if this was working previous the update ? I tried using it with the previous version and it's still broken. 

If it's working on previous versions for you can you please share and instance where it is working with an older version, it will help a lot, thank you!

**Comment by AndreeaCristinaRadacina** [comment]
Sure:

- https://conscioushearing.s1-tastewp.com/wp-admin
- user
- bb)ES1i0KuNOl*Wvjp6BTUVr

**Comment by GrigoreMihai** [comment]
@AndreeaCristinaRadacina Thank you for the details, I'm still struggling to replicate the issue, even on your instance after updating the plugin the default value is still selected: https://vertis.d.pr/v/mhwlUu . 

Are there any additional steps that you took when replicating ?

**Comment by AndreeaCristinaRadacina** [comment]
Hey @GrigoreMihai,

Thank you for your patience, and I apologize for the delay.

The problem occurs when using the radio input as a conditional field. I set this up in PPOM; you can test it on the Test product.
There is a radio field displayed under conditions, that ignores the default value and a simple radio input that displays it without problem.

What I also noticed is that the same problem occurs to me even before the update in 32.0.9, so I am not exactly sure why they reported this now.
