### ISSUE TITLE
File Upload opens multiple modals 

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/woocommerce-product-addon#268]
### Description

A user reported that he cannot use the file upload anymore using the Select button, but only by using drag and drop.

I was able to replicate this on my website and it happens when using more file inputs with conditions.

ref:https://secure.helpscout.net/conversation/2536174155/408110?viewId=212385

### Step-by-step reproduction instructions

1. Create a new meta group
2. Add a select field with two options: First file, Second file
3. Add a file input and add the condition to show it when First file is selected
4. Add a new file input and add the condition to show it when Second file is selected
5. Save everything and check the product 

You can also use this export if you want - 
[ppom-meta-1710161402.csv](https://github.com/Codeinwp/woocommerce-product-addon/files/14558795/ppom-meta-1710161402.csv)

### Screenshots, screen recording, code snippet or Help Scout ticket

- https://crushhospital.s2-tastewp.com/
- JCvSBDlORoYBC@4P0GubntG3
- Themeisle

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by AndreeaCristinaRadacina** [comment]
It was solved here - https://github.com/Codeinwp/ppom-pro/issues/229, but it happens again.

I tested on my instance, the user's instance, and on a fresh instance.

**Comment by irinelenache** [comment]
+1 https://secure.helpscout.net/conversation/2547326645/410699/?folderId=212385

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://secure.helpscout.net/conversation/2546477793/410585/?folderId=212385
