### ISSUE TITLE
Greater/less than conditions won't work

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/woocommerce-product-addon#275]
### Description

While working on a ticket, I noticed that the conditions that imply numerical fields cannot be configured because there is no text area.

### Step-by-step reproduction instructions

1. Create a meta group
2. Insert a quantity field
3. Insert a select field and enable conditions
4. Set the condition as follows: Quantity is greater than

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="1379" alt="image" src="https://github.com/Codeinwp/woocommerce-product-addon/assets/86592992/1b28b23c-b5e2-452d-867d-2288edf7e903">

### Is the issue you are reporting a regression

No

**Comment by selul** [comment]
part of https://github.com/Codeinwp/ppom-pro/issues/429

**Comment by StenderIternum** [comment]
@selul 
> part of https://github.com/Codeinwp/ppom-pro/issues/429

Have the same issue, with a "greater than" select field - The condition won't match, and this issue that you have linked, doesn't seem to exist.  If you have closed the issue, is there a solution then?
