### ISSUE TITLE
PPOM column replaced Product Tags column

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/woocommerce-product-addon#292]
### Description

I am not sure if it's a bug or intentional, but a user reported that the PPOM column has replaced the Product Tags column on this page: https://yoursite.com/wp-admin/edit.php?post_type=product.

### Step-by-step reproduction instructions

1. Activate PPOM and WooCommerce 
2. Go to https://yoursite.com/wp-admin/edit.php?post_type=product
3. You won't see the tag column

### Screenshots, screen recording, code snippet or Help Scout ticket

Without PPOM: https://vertis.d.pr/i/ih6pf1
With PPOM: https://vertis.d.pr/i/01VEvM

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
@poonam279  I've reviewed this issue and fixed it here - https://github.com/Codeinwp/woocommerce-product-addon/pull/346
