### ISSUE TITLE
[DEV] Add random element in plugin version for DEV files.

### ISSUE THREAD

**Issue by Soare-Robert-Daniel** [Codeinwp/woocommerce-product-addon#313]
When making the dev build in PR, we can assign random elements to the plugin version like `30.2.0-dev234543` to invalidate the cache on the hosting server and make it serve the new files.

**Comment by selul** [comment]
I think using the commit sha might be better vs something random

**Comment by Soare-Robert-Daniel** [comment]
In the build workflow, we can use `sed` to make the switch.

```bash
sed -i "s/define( 'PPOM_VERSION', '[0-9a-f]*' );/define( 'PPOM_VERSION', '${{ steps.get_sha.outputs.sha }}' );/" woocommerce-product-addon.php
```
