### ISSUE TITLE
Latest version is not available on wp.org

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/woocommerce-product-addon#315]
### Description

Version 32.0.23, released yesterday is not available on wp.org

### Step-by-step reproduction instructions

![Annotation on 2024-07-02 at 19-03-51](https://github.com/Codeinwp/woocommerce-product-addon/assets/3266155/79219e7f-30aa-4b14-98be-38861bc020bf)

### Is the issue you are reporting a regression

No

**Comment by vytisbulkevicius** [comment]
@rodica-andronache,

Thanks for noticing, it's fixed now.
