### ISSUE TITLE
Fields appear as required even if they're not

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/woocommerce-product-addon#316]
### Description

Users reported that the products using PPOM have errors regarding required fields, even if the fields are not required.

### Step-by-step reproduction instructions

1. Update to the latest version of PPOM
2. Import the attached CSV (or create a meta group with some not required fields)
[ppom-meta-1719991023.csv](https://github.com/user-attachments/files/16078498/ppom-meta-1719991023.csv)

3. Attach it to a product
4. Go to the product and don't fill in those not required fields, then try to add to cart

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="1395" alt="image" src="https://github.com/Codeinwp/woocommerce-product-addon/assets/86592992/f8ca9753-60db-44eb-9ba0-cc26049c1b27">
<img width="1518" alt="image" src="https://github.com/Codeinwp/woocommerce-product-addon/assets/86592992/fa196f07-0660-4757-b5b7-33895d23716a">

ref: https://wordpress.org/support/topic/wont-add-to-cart/#post-17863642

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://secure.helpscout.net/conversation/2591053028/418169?viewId=212390

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://secure.helpscout.net/conversation/2642020955/424336?viewId=212385

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://wordpress.org/support/topic/addition-error-in-cart-and-checkout/#post-17865516

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina I've reviewed this issue and fixed it with this PR https://github.com/Codeinwp/woocommerce-product-addon/pull/318

**Comment by AndreeaCristinaRadacina** [comment]
@girishpanchal30, it's working as expected now. Thank you!

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://wordpress.org/support/topic/ppom-dont-add-product-to-the-cart/
