### ISSUE TITLE
Collapse became open by default after the release

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/woocommerce-product-addon#322]
### Description

After the release, the collapse input does not work correctly anymore. A user reported that it is by default open, even if the "by default open" feature is not checked.

### Step-by-step reproduction instructions

1. Install PPOM 32.0.24
2. Go to PPOM inputs
3. Add a collapse input and some fields (e.g. Text)
4. Attach it to a product
5. Update to the latest version

### Screenshots, screen recording, code snippet or Help Scout ticket

https://secure.helpscout.net/conversation/2656748427/427123?viewId=212385

See live behavior - https://littleroll.s2-tastewp.com/product/banana-sweater/

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina I've reviewed this issue and fixed it here https://github.com/Codeinwp/woocommerce-product-addon/pull/323

**Comment by AndreeaCristinaRadacina** [comment]
I tested and everything works fine now! The collapse is again closed by default.
