### ISSUE TITLE
Warnings on the Changelog page

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/woocommerce-product-addon#329]
### Description

![Annotation on 2024-08-07 at 10-44-06](https://github.com/user-attachments/assets/829a0d10-8505-4cdb-ba43-0e5d671ae7ab)
![Screenshot on 2024-08-07 at 10-43-15](https://github.com/user-attachments/assets/eaa02596-d90a-4354-9f04-4f60c6ecf663)

### Step-by-step reproduction instructions

Go to WooCommerce > PPOM Fields > Changelog

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
@rodica-andronache I've reviewed this issue and fixed it here - https://github.com/Codeinwp/woocommerce-product-addon/pull/332
