### ISSUE TITLE
Used PPOM Fields are not passed in the Cart when trying to re-order a product

### ISSUE THREAD

**Issue by Skystream96** [Codeinwp/woocommerce-product-addon#33]
### Description:

It seems like if you use PPOM fields with Woocommerce to make an order everything behaves correctly. The issue appears if you try to make that order again (after completion) as the PPOM fields are not moved over to the cart.

They appear when you see the order, but when you click on "Order Again" and you are redirected to the cart, the options from PPOM are not there anymore.

### How to reproduce:

1. Have Woocommerce and PPOM Installed
2. Create a new product if you don't have one already
3. Create a Meta Group in PPOM and create a field (in my example I used select and Text)
4. Attach the PPOM fields to a product
5. Create a coupon so you can order the product for testing purposes => Order the product
6. Observe how the PPOM fields appear in the Cart and Checkout
7. Go to Woocommerce > Products > Orders > mark the order as completed (to make the Order Again button appear)
8. Go to My Account > View Order > Notice how the PPOM fields appear here
9. Click on Order again
10. Observe how the PPOM fields have vanished from the cart

### Expected behaviour:
PPOM fields remain when using the Order Again functionality

### Current behaviour:
PPOM fields are dissapear when using the Order Again functionality

### Reference:
[Screencast](https://vertis.d.pr/CsULvJ)

###Testing Instance:
Site name: Snotty Fight
URL: https://snottyfight.s1-tastewp.com
Username: mateithemeisle
Password: tvahe-aLVzg

[User reported here.](https://secure.helpscout.net/conversation/2004015865/336195?folderId=212390)

### Technical info
* WordPress version: 6.0.2
* Woocomerce version: 6.8.2
* PPOM Version: 30.1.4

**Comment by MarinescuLucia** [comment]
Hiii! :) Is there any update about this issue?

**Comment by mskapusuz** [comment]
Hey, @MarinescuLucia :)

Unfortunately, there is no update yet. I'm planning to handle it probably in 1-2 weeks.

**Comment by mskapusuz** [comment]
Latest update @MarinescuLucia @Skystream96 

I've added compatibility support for the Order Again feature of WooCommerce. From now on, all PPOM fields of the Order Items also will be cloned to the cart. I've just moved the PR to the test column, I hope we will be released it in this week or the next week. Fyi. 🚀
