### ISSUE TITLE
Review changelog to improve formatting 

### ISSUE THREAD

**Issue by selul** [Codeinwp/woocommerce-product-addon#341]
Changelog has a few entries which is acting strange https://vertis.d.pr/i/8ARLxC, we can look into fixing the parsing or list the content as it is without tabs and such.

**Comment by girishpanchal30** [comment]
I've reviewed and fixed the changelog format issue.

Free: https://github.com/Codeinwp/woocommerce-product-addon/pull/366
Pro: https://github.com/Codeinwp/ppom-pro/pull/453

**Comment by selul** [comment]
@girishpanchal30 I dont think this is enough, we need either to fix the parsing to be consistent  or display changelog as it is without any tabs and anything. 

The thing with edits on the changelog is that it can always come back when a new version is using some strange chars/format.

**Comment by girishpanchal30** [comment]
@selul I've fixed the parsing issue, please check with this PR #366
