### ISSUE TITLE
Non required fields appear as required

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/woocommerce-product-addon#369]
### Description

A user reported that non-required fields appear as required. We have already fixed this issue here: https://github.com/Codeinwp/woocommerce-product-addon/issues/316, but there is a new finding. The issue occurs if a required field is added before the non-required field.

### Step-by-step reproduction instructions

1. Create a meta group and add a required field first
2. Now add a non-required field
3. Attach it to a product
4. Go to the product and don't fill in those not required fields, then try to add to cart

### Screenshots, screen recording, code snippet or Help Scout ticket

![Screenshot on 2024-09-11 at 22-54-30](https://github.com/user-attachments/assets/60e71d87-be25-4838-b566-ba46ac75da55)
<img width="1222" alt="Screenshot 2024-09-11 at 10 55 04 PM" src="https://github.com/user-attachments/assets/b5f4afab-2fab-4732-9915-1b0e5d917946">

HS Ticket: https://secure.helpscout.net/conversation/2702498320/433263?folderId=212385

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
I've reviewed this issue and fixed it here - https://github.com/Codeinwp/woocommerce-product-addon/pull/376

**Comment by poonam279** [comment]
@girishpanchal30 I have checked and the issue is fixed.
