### ISSUE TITLE
Conditional Logic Not Working with Checkbox Selection 

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/woocommerce-product-addon#398]
### Description

Conditional logic based on checkbox selections no longer works. Previously, it was possible to display fields based on the user's choice of a checkbox option. However, this functionality is currently broken, and the conditional fields do not show based on the checkbox selection.

### Step-by-step reproduction instructions

1. Create a checkbox field using 2-3 options (eg: first, second, third)
2. Add the max checked option
3. Create another field text in the same meta-group
4. Set the visibility condition of the text field based on the selection of the checkbox.(eg https://vertis.d.pr/i/LGQ1P9)
5. Check the conditional logic on the frontend.

### Screenshots, screen recording, code snippet or Help Scout ticket

https://wordpress.org/support/topic/les-lignes-add-options-napparaissent-plus-dans-les-conditions/

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by poonam279** [comment]
New finding: The condition works if we do not add the Max Checked option. To replicate the issue you need to add max checked option. Screenshot: https://vertis.d.pr/i/MY04uR

**Comment by selul** [comment]
@Soare-Robert-Daniel can you prioritize this?
