### ISSUE TITLE
Max Checked Option Limit Not Working

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/woocommerce-product-addon#399]
### Description

In the recent version of the plugin, the "max checked" option is not functioning correctly. Even after setting a maximum limit for the number of selections allowed, users are still able to select all available options, bypassing the limit.

### Step-by-step reproduction instructions

1. Add a checkbox field with multiple options.
2. Set the "max checked" limit (e.g., limit to 2 selections).
3. Test the checkbox field on the frontend.

### Screenshots, screen recording, code snippet or Help Scout ticket

Screenshots: https://vertis.d.pr/i/ejrqVa https://vertis.d.pr/i/UEqzxq

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by selul** [comment]
@poonam279 was this working fine before?

**Comment by poonam279** [comment]
@selul I have checked by rolling back to the previous versions, and it's not working.

**Comment by selul** [comment]
ok, in this case I will not consider a regression.

**Comment by selul** [comment]
@Soare-Robert-Daniel can you have a look if this is an easy fix too?
