### ISSUE TITLE
PPOM field association by category not saving

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/woocommerce-product-addon#403]
### Description

The system does not remember the category assigned to the PPOM meta if it is set in the 'Product Meta Basic Settings' page. This category is not saved, and therefore, the fields do not apply to the products.

If the category is set on the main PPOM Field Groups page using 'Attach to products,' it works correctly. Scereenshot: https://vertis.d.pr/i/FavT7Y
However, when editing the field again, saving the changes causes the system to forget the category association.

### Step-by-step reproduction instructions

1. Create a meta-group
2. Click Attach to products option that appears at the top of the meta field page. Screenshot: https://vertis.d.pr/i/3E9deJ
3. Set a category under the **display in specific product category dropdown**
4. Save the changes
5. Check the category dropdown again. You won't see the assigned category there. 

### Screenshots, screen recording, code snippet or Help Scout ticket

HS Ticket: https://secure.helpscout.net/conversation/2727731447/436454

### Is the issue you are reporting a regression

No

**Comment by selul** [comment]
this is a regression since category it was working fine before.

**Comment by selul** [comment]
@Soare-Robert-Daniel can you prioritize this?
