### ISSUE TITLE
Unable to reorder the fields in a meta group

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/woocommerce-product-addon#404]
### Description

We are not able to reorder the PPOM fields in a meta-group.

### Step-by-step reproduction instructions

1. Create a meta group with three fields
2. Move any field up or down in the order.
3. Click the "Save Fields" button.
4. Check if the new field order is saved.

### Screenshots, screen recording, code snippet or Help Scout ticket

https://secure.helpscout.net/conversation/2727803532/436462?viewId=212385

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by rodica-andronache** [comment]
+1 https://secure.helpscout.net/conversation/2728135091/436499?viewId=212385
