### ISSUE TITLE
Multiple Checked options not working anymore

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/woocommerce-product-addon#425]
### Description

For a checkbox field, we have the option to have some of the options checked by default. When you choose multiple options to be selected by default, they don't appear as selected

![Image](https://github.com/user-attachments/assets/e4591e53-d81d-41f1-87bf-904745ddab64)
![Image](https://github.com/user-attachments/assets/6c78f528-704d-42e5-a42c-b1e02a3952a5)

### Step-by-step reproduction instructions

1. Create a Checkbox field with multiple choices: Yes, No, Maybe
2. Add multiple values for the "Checked options" option, for example "Yes, No" -> The values don't appear as checked on the frontend
3. If you add just one value for "Checked options" it seems to work -> The value is checked

### Screenshots, screen recording, code snippet or Help Scout ticket

https://secure.helpscout.net/conversation/2748993821/439094?viewId=212385

From what I've tested, it worked in version 32.0.27, so I marked it as a regression, hope it's ok.

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by selul** [comment]
@Soare-Robert-Daniel can you prioritize this regression aswell.
