### ISSUE TITLE
Notice: Function _load_textdomain_just_in_time was called incorrectly.

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/woocommerce-product-addon#438]
### Description

A user reported that they are seeing this error after updating to WordPress version 6.7.1 at the top of the screen on the backend and frontend of my site:

Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the ppom-addon-imageselect domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in /home/candleswithchar/public_html/wp-includes/functions.php on line 6114

### Step-by-step reproduction instructions

I couldn't replicate it. 

### Screenshots, screen recording, code snippet or Help Scout ticket

https://wordpress.org/support/topic/notice-function-_load_textdomain_just_in_time-was-called-incorrectly-6/

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
@poonam279 I reviewed the `PPOM Addon` and couldn't find the `ppom-addon-imageselect` text domain used in our plugin. The issue might be related to theme or another plugin.

cc @vytisbulkevicius 

Thanks

**Comment by selul** [comment]
@poonam279 in the future if you can't replicate the issue and can add enough details and I think is better to don't report it since is impossible for the developer to submit the fix.
