### ISSUE TITLE
The options of the meta field are not visible on smaller window size

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/woocommerce-product-addon#50]
If the window is smaller, the options of the meta field are not displayed anymore:
<img width="887" alt="image" src="https://user-images.githubusercontent.com/86592992/195033403-183052a2-7040-4c1f-bea5-3e295e62e083.png">

**Comment by AndreeaCristinaRadacina** [comment]
Also, do you think it would be better to add an offset of the modal to avoid appearing stuck to the top navbar?

**Comment by mskapusuz** [comment]
> Also, do you think it would be better to add an offset of the modal to avoid appearing stuck to the top navbar?

Thanks for the suggestion @AndreeaCristinaRadacina I think it does makes sense. I've left 30px spacing in the top just now.

![Screen Shot 2023-02-26 at 16 25 18](https://user-images.githubusercontent.com/25361626/221413192-83c03df4-a992-4541-a2fc-f7f85bb308f5.png)
