### ISSUE TITLE
Option Price is not passed in the Total Price with the latest Update

### ISSUE THREAD

**Issue by Skystream96** [Codeinwp/woocommerce-product-addon#56]
With update 32.0.0 the option price are no longer added to the total product price. To get this functionality back, you need to rollback the plugin to 31.0.0.

How to reproduce:
1) Have the latest update for PPOM and Woocommerce 7.0
2) Attach meta to a product and make sure you have PPOM fields with added price
3) Select some options for the product that should increase the price of the product
4) Add the product to cart
5) Notice how the option price was not passed. Only the product price remained.

Expected Result:
The Total Product Price includes the PPOM fields too

Current Result:
Only the initial product price is passed to the cart

Refference:
[Screencast](https://vertis.d.pr/v/lcvNtn)

[User 1 Reported here](https://wordpress.org/support/topic/not-adding-to-cart-after-woocommerce-update/)
[User 2 Reported here](https://wordpress.org/support/topic/ppom-not-working-anymore-since-upgrading-to-woocommerce-7-0-0/)

System:
PPOM Version: 32.0.0
Woocommerce Version: 7.0
WP Version: 6.0.3

**Comment by mskapusuz** [comment]
from my first view, pro users (if PPOM Pro is activated too) are not affected by this issue. That's strange.
